### PR TITLE
Fix execution script

### PR DESCRIPTION
**Pull request by EricSalemi**
Pull request to fix the execution scripts in `bin` directory.

Main change is that relevant sub-projects (root, gui and retrace) now generates an extra self-contained jar (`fat` classifier) with all necessary dependencies. The `bat` and `shell` scripts are using the new artifact. Note that the fat jars are quite large and are not included in the maven publication.

### CODE REVIEW

**Comment by EricLafortune** [comment]
The fat jar (and the scripts in `bin`) don't seem to work yet because they don't have the expected manifests. However, only the following jars should have corresponding fat jars:
* `base/build/libs/base-7.0.0.jar` (for use in `bin/proguard.*`)
* `gui/build/libs/gui-7.0.0.jar` (for use in `bin/gui.*`)
* `retrace/build/libs/retrace-7.0.0.jar` (for use in `bin/retrace.*`)

The jars don't need the custom manifests; only the fat jars need them so they can be executed.

We don't need the combined jars in `build/libs`. proguard-parent doesn't have a jar. The combined fat jar is huge because it contains all Gradle dependencies (which we never need in a fat jar).

**Comment by EricLafortune** [comment]
That's right. None of the scripts in `bin` need the main `build/libs`.

**Comment by EricSalemi** [comment]
I tested the 3 bash scripts and they work on my machine.

I added code to dynamically load version identifier from the manifest in the ProGuard class, which nicely shows up on the command line. 

Note that the GUI still has the old 6.2.2 version identifier. I don't think it will be easy to inject it dynamically in the `GUIResources.properties`. I will simply remove the version.

**Comment by EricLafortune** [comment]
The scripts work! Nice injection of the version number.
* We still need the injection in the fat GUI jar -- it calls ProGuard, which prints it out.
* I've simplified and documented getVersion() (we would also have to close the input stream otherwise).
* `bin/base.*` should remain `bin/proguard.*`

We can squash and merge this PR when we're done.

**Comment by EricSalemi** [comment]
>     * We still need the injection in the fat GUI jar -- it calls ProGuard, which prints it out.

I guess reverting 7c7d21 would be enough?

>     * I've simplified and documented getVersion() (we would also have to close the input stream otherwise).

Thanks.
I had taken the snippet from SO.
Didn't see Java was providing an implementation for it.

**Pull request merged**
