### PR TITLE
Add distribution files

### PR DESCRIPTION
**Pull request by EricSalemi**
Same logic as for https://github.com/Guardsquare/proguard-core/pull/9.

@EricLafortune @dzan What else would you add in the dist files?

### CODE REVIEW

**Comment by EricLafortune** [comment]
Looking at `build/distributions/parent-7.0.0.tar`...

* The `lib` directory with the fat jars looks good, also compatible with `bin`.

Still missing:
* `bin`
* `docs/manual`,... It would be fine to simply copy all of `docs`
* `LICENSE`, `LICENSE_exception.md`

Older versions also contained the entire repository:
* `gui/src`,`gui/build.gradle`,...
* `retrace/src`, `retrace/build.gradle`,...
* `base/src`, `base/build.gradle`,...
* .....

It may be a clean option to make this a CLI-binary-only archive, without the source code or the build files. Developers should then get the source codet from the real git repository.

**Comment by EricSalemi** [comment]
> It may be a clean option to make this a CLI-binary-only archive, without the source code or
> the build files. Developers should then get the source codet from the real git repository.

Source code is also available with the `sources` maven classifier.

I will let you decide on this one.

**Comment by EricLafortune** [comment]
Yes, let's just package the binaries + documentation in the tar/zip.

**Comment by EricSalemi** [comment]
All comments have been integrated then.

Can you accept the PR?

**Comment by EricLafortune** [comment]
Looks good and the binaries work!

The base directory and archive name should still be `proguard-...`

**Comment by EricSalemi** [comment]
>     * The base directory and archive name should still be `proguard-...`

You mean like `build/distributions/proguard-7.0.0.zip`?

>     * Is it easy to make it .tar.gz?

I will look into that.

**Pull request merged**
