### PR TITLE
Run CI on Windows in addition to Ubuntu

### PR DESCRIPTION
**Pull request by simonschiller**
Running CI on multiple operating systems should helpto stay compatible with all of them (see #272). I expect this to fail for now. Would be great if I could get approval to run this workflow (if you would be ok with the change) to see what breaks so we can take a look and potentially fix the problems.

### CODE REVIEW

**Comment by mrjameshamilton** [comment]
Thanks for the PR! Good idea! Indeed, it's failing right now :)

**Comment by simonschiller** [comment]
I migrated all occurences I found in the plugin to [Kotlin's resolve](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/resolve.html), that should fix the problem. Not sure if I missed any or if that's enough to fix the issues. Maybe you can trigger CI again and if I didn't catch everything use this as a basis 😄

**Comment by mrjameshamilton** [comment]
Thanks @simonschiller! The tests are now passing after a couple more changes :tada: 

Closes: #272

**Comment by simonschiller** [comment]
Amazing! Will this be included in the upcoming 7.3.0 release?

**Comment by mrjameshamilton** [comment]
> Amazing! Will this be included in the upcoming 7.3.0 release?

Yes, it'll be there :)

**Pull request merged**
